python ./src/ror_refine_batch.py --input "./getfiles/all_papers_2026-03-14_enriched.jsonl" 
python ./src/ror_refine_batch.py --input "./getfiles/all_papers_2026-03-21_enriched.jsonl"
python ./src/ror_refine_batch.py --input "./getfiles/all_papers_2026-03-28_enriched.jsonl"
python ./src/ror_refine_batch.py --input "./getfiles/all_papers_2026-04-04_enriched.jsonl"
python ./src/ror_refine_batch.py --input "./getfiles/all_papers_2026-04-11_enriched.jsonl"
python ./src/ror_refine_batch.py --input "./getfiles/all_papers_2026-04-18_enriched.jsonl"
